import { Container } from "@chakra-ui/react";
import Head from "next/head";
import Header from "../components/Header";
import ProductList from "../components/ProductList";
import { font } from "./_app";

export default function Home({ products }) {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Container maxW="1400px" className={font.className}>
        <Header />
        <ProductList products={products} />
      </Container>
    </>
  );
}

export async function getStaticProps() {
  const res = await fetch("https://fakestoreapi.com/products");

  const products = await res.json();

  return {
    props: {
      products,
    },
  };
}
